# yaml-language-server: $schema=https://json-schema.axonivy.com/14.0-dev/config/rest-clients-1.json
RestClients:
  #The Snowflake SQL API is a REST API that you can use to access and update data in a Snowflake database. 
  Snowflake-SQL-API:
    Name: Snowflake SQL API
    Url: ${ivy.var.snowflakeConnector.locatorUrl}
    Icon: res:/webContent/icons/logo.png
    Features:
      - com.axonivy.connector.snowflake.auth.SnowflakeAuthFeature
      - com.axonivy.connector.snowflake.auth.DataJsonFeature
    Properties:
      AUTH.JWTToken: ${ivy.var.snowflakeConnector.jwtToken}
    OpenAPI:
      SpecUrl: file:///C:/Users/phhung/Downloads/sqlapi.yaml
      Namespace: com.snowflakecomputing.org.account.client
    LegacyUUID: 0bfd805c-83c8-4866-ac7c-0c3119cc72e0
