name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v6
    secrets:
      mvnArgs: -Dsnowflake.locatorUrl=${{ secrets.LOCATOR_URL }} -Dsnowflake.locator=${{ secrets.LOCATOR }} -Dsnowflake.username=${{ secrets.USERNAME }} -Dsnowflake.privateKey=${{ secrets.PRIVATE_KEY }}
