name: E2E-Build

on:
  schedule:
    - cron:  '0 1 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  checks: write

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/ci.yml@v6
    secrets:
      mvnArgs: -Dsnowflake.locatorUrl=${{ secrets.LOCATOR_URL }} -Dsnowflake.locator=${{ secrets.LOCATOR }} -Dsnowflake.username=${{ secrets.USERNAME }} -Dsnowflake.privateKey=${{ secrets.PRIVATE_KEY }} -DtestEnvironment=E2E
